// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
)

// Defines values for Outcome.
const (
	Ineligible Outcome = "ineligible"
	NotLocked  Outcome = "not_locked"
	Unlocked   Outcome = "unlocked"
)

// Valid indicates whether the value is a known member of the Outcome enum.
func (e Outcome) Valid() bool {
	switch e {
	case Ineligible:
		return true
	case NotLocked:
		return true
	case Unlocked:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	AccountRestricted    ProblemCode = "account_restricted"
	AttestationRequired  ProblemCode = "attestation_required"
	AuditFailed          ProblemCode = "audit_failed"
	BadRequest           ProblemCode = "bad_request"
	DirectoryError       ProblemCode = "directory_error"
	InvalidCredentials   ProblemCode = "invalid_credentials"
	NoSession            ProblemCode = "no_session"
	PresenceMismatch     ProblemCode = "presence_mismatch"
	RateLimited          ProblemCode = "rate_limited"
	SessionExpired       ProblemCode = "session_expired"
	VoucherIsClaimant    ProblemCode = "voucher_is_claimant"
	VoucherMismatch      ProblemCode = "voucher_mismatch"
	VoucherNotAuthorised ProblemCode = "voucher_not_authorised"
	WrongStage           ProblemCode = "wrong_stage"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case AccountRestricted:
		return true
	case AttestationRequired:
		return true
	case AuditFailed:
		return true
	case BadRequest:
		return true
	case DirectoryError:
		return true
	case InvalidCredentials:
		return true
	case NoSession:
		return true
	case PresenceMismatch:
		return true
	case RateLimited:
		return true
	case SessionExpired:
		return true
	case VoucherIsClaimant:
		return true
	case VoucherMismatch:
		return true
	case VoucherNotAuthorised:
		return true
	case WrongStage:
		return true
	default:
		return false
	}
}

// Defines values for Stage.
const (
	AwaitingClaim        Stage = "awaiting_claim"
	AwaitingConfirmation Stage = "awaiting_confirmation"
	Complete             Stage = "complete"
	Start                Stage = "start"
)

// Valid indicates whether the value is a known member of the Stage enum.
func (e Stage) Valid() bool {
	switch e {
	case AwaitingClaim:
		return true
	case AwaitingConfirmation:
		return true
	case Complete:
		return true
	case Start:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Department  *string `json:"department,omitempty"`
	Description *string `json:"description,omitempty"`
	DisplayName string  `json:"displayName"`
	Mail        *string `json:"mail,omitempty"`
	Title       *string `json:"title,omitempty"`
	Username    string  `json:"username"`
}

// Confirmation defines model for Confirmation.
type Confirmation struct {
	// Attest The voucher attests that they are with the user in person and have confirmed their identity.
	Attest   bool   `json:"attest"`
	Password string `json:"password"`

	// Username The voucher's username, which must be the account that started the session.
	Username string `json:"username"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Password string `json:"password"`

	// Username sAMAccountName, userPrincipalName or DOMAIN\sAMAccountName.
	Username string `json:"username"`
}

// Info defines model for Info.
type Info struct {
	// ConfirmWindowSeconds How long the voucher has to confirm after the user enters their details.
	ConfirmWindowSeconds int `json:"confirmWindowSeconds"`

	// HelpText Optional extra guidance shown when the locked-out user enters their details.
	HelpText *string `json:"helpText,omitempty"`

	// SessionLifetimeSeconds How long a session lasts from the voucher signing in.
	SessionLifetimeSeconds int `json:"sessionLifetimeSeconds"`

	// Title Page title.
	Title string `json:"title"`

	// VoucherDescription Who may vouch for a user, in words the user understands.
	VoucherDescription string `json:"voucherDescription"`
}

// Outcome * `not_locked` - the password works, so the account isn't locked.
// * `unlocked` - the account's lockout was cleared after the voucher confirmed.
// * `ineligible` - this account can't be unlocked by self-service.
type Outcome string

// Problem defines model for Problem.
type Problem struct {
	Code    ProblemCode `json:"code"`
	Message string      `json:"message"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// SessionState defines model for SessionState.
type SessionState struct {
	// ClaimedUsername The username entered in step 2.
	ClaimedUsername *string `json:"claimedUsername,omitempty"`

	// ConfirmBy In `awaiting_confirmation`, when the user's details expire and must be entered again.
	ConfirmBy *time.Time `json:"confirmBy,omitempty"`

	// ExpiresAt When the session expires.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Message A human-readable explanation of the outcome.
	Message *string `json:"message,omitempty"`

	// Outcome * `not_locked` - the password works, so the account isn't locked.
	// * `unlocked` - the account's lockout was cleared after the voucher confirmed.
	// * `ineligible` - this account can't be unlocked by self-service.
	Outcome *Outcome `json:"outcome,omitempty"`
	Stage   Stage    `json:"stage"`
	Target  *Account `json:"target,omitempty"`
	Voucher *Account `json:"voucher,omitempty"`
}

// Stage defines model for Stage.
type Stage string

// SubmitClaimJSONRequestBody defines body for SubmitClaim for application/json ContentType.
type SubmitClaimJSONRequestBody = Credentials

// ConfirmVouchJSONRequestBody defines body for ConfirmVouch for application/json ContentType.
type ConfirmVouchJSONRequestBody = Confirmation

// SubmitVoucherJSONRequestBody defines body for SubmitVoucher for application/json ContentType.
type SubmitVoucherJSONRequestBody = Credentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetInfo Settings the web interface needs to render
	// (GET /info)
	GetInfo(ctx *echo.Context) error
	// CancelSession Abandon the current unlock session
	// (DELETE /session)
	CancelSession(ctx *echo.Context) error
	// GetSession The current unlock session of this browser
	// (GET /session)
	GetSession(ctx *echo.Context) error
	// SubmitClaim Step 2 - the locked-out user enters their username and password
	// (POST /session/claim)
	SubmitClaim(ctx *echo.Context) error
	// ConfirmVouch Step 3 - the voucher confirms the user's identity and signs in again to unlock
	// (POST /session/confirm)
	ConfirmVouch(ctx *echo.Context) error
	// SubmitVoucher Step 1 - an authorised colleague signs in and starts a session
	// (POST /session/voucher)
	SubmitVoucher(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetInfo(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInfo(ctx)
	return err
}

// CancelSession converts echo context to params.
func (w *ServerInterfaceWrapper) CancelSession(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelSession(ctx)
	return err
}

// GetSession converts echo context to params.
func (w *ServerInterfaceWrapper) GetSession(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSession(ctx)
	return err
}

// SubmitClaim converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitClaim(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitClaim(ctx)
	return err
}

// ConfirmVouch converts echo context to params.
func (w *ServerInterfaceWrapper) ConfirmVouch(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConfirmVouch(ctx)
	return err
}

// SubmitVoucher converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitVoucher(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitVoucher(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/info", wrapper.GetInfo, options.OperationMiddlewares["getInfo"]...)
	router.DELETE(options.BaseURL+"/session", wrapper.CancelSession, options.OperationMiddlewares["cancelSession"]...)
	router.GET(options.BaseURL+"/session", wrapper.GetSession, options.OperationMiddlewares["getSession"]...)
	router.POST(options.BaseURL+"/session/voucher", wrapper.SubmitVoucher, options.OperationMiddlewares["submitVoucher"]...)
	router.POST(options.BaseURL+"/session/claim", wrapper.SubmitClaim, options.OperationMiddlewares["submitClaim"]...)
	router.POST(options.BaseURL+"/session/confirm", wrapper.ConfirmVouch, options.OperationMiddlewares["confirmVouch"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fjfj9u4Ef5XBmqBtAetNz+ufTDQBye59ha4ywZwevdwDmxaHEm8SEOVQ9kxgv3fC5KifnjlzT5s2gJ9",
	"syVqOJz55ptv+CXJdN1oQrKcLL8kBrnRxOj/vDd6X2HtfmaaLJJ1P0XTVCoTVmm6/p01uWeclVgL9+uP",
	"BvNkmfzherB7Hd7ydbR3d3eXJhI5M6pxZpJl8qFEMPivFtlCLlSFcpG4Vd2nzvIqy3QbXGiMbtBYFdyU",
	"2Ahj6849e2owWSZsjaIiOd9o7r3iphKnd6LG2fe1UNXsC6tsNf9Jy2ho3t5dmrhzKoMyWf42rJz68TGN",
	"3+n975hZZ/SNplyZWsSDTIMgrEW2IRzngT3oNivRQFjDYEthwZZ4AmEQjsqW7h84X0ARNGhYEwiSUIoD",
	"QhY2RulWKQNKIlllT4uk93KvdYWCnJuNYD5qI50ruXb+JsvhoQvn55+QClsmyxfPX36fJrWi/kH6cCwv",
	"Hu0ZQ1yXwrFUWQl1yxb26E8mAnTCwdkKY8NhgJFZaVpM/Xr5l79+xa3LWRydtEvJbC4N+iCKiu+n8j8X",
	"QV793FXVOx85t/K9UZSpRlTuEWgDb29/Xt2822ymi79FyOYidUO5vh+iDpK/KpL6uMZMk+T7x/tRH6HS",
	"VIAdkAKlYLA6ghpEbtEM8EeyaLgDukQrVMUjnCuyWKBxjpVYNR/w80zJ3fofogL8bI2AolVSUIbApT4S",
	"HEskv1+ls08or3RrH7X1kM8OtD+pHK2q8evHFxHnUAm2DLnR9SQmrApSVICi+bP2TDfd4L0oEPy7WT87",
	"62+n/Ds18WupoRan4Ank2oDw0UhBEThQ8JCbliQatoLkXFzO8BVcnnXiYgTTeVzNwfK2tZmeK6nvYEfa",
	"bkNyd3Dl3Y8Idyf6xCmwntCSYnpmOzwsNvQd7FqaGuhWPmO/ykHmKBiyCoVBOcJwTGhP2cGcIqxUofYV",
	"BoOK+70z4fbeI8QtYX8Cxiq/YjQHleFi4yKG1NYurMPZkjSJnyRpMuyQfLyXmnSsJM4LWfogRvt7Ibed",
	"DvBWD6JScpuN6DJNOte3Bt0GmfUOGGFxW6lahb+kt12Sh3Rv8XPj4ZEmR6Op2LIVhScgg4yU4bZWXAub",
	"lQNutu7AorWlNopRjl4o3maVULUgO3o6shDo37frbY9M1+YNZlab0xaN0cYtbKWy26B6ZqNXI7MoHqEm",
	"fDSH9XPAXYdYrK2wOJMOdyKU/3yw50bqDoyF0pUqW2zg5SwNdFh8fbpv7YZgJ45CWUXFNhvpm1068KTb",
	"7hlHRoSQRK9OYouPfohCBAbru6YUFq9cic85Fizxys7RUrd5JM5u7eONj3I2Nb2Csq0FXRkUUuwrdKYr",
	"Qf7YoHO/qw7sMhtOPTDPQ1o7EpTrF1YUX12/9osc1wtToP3a8ijGB5p/9BdnmGV7EarR70gOXrm5gukh",
	"4+A6eTDWyKmfbSq0c5zk3FCdtpgmaD0iv44VXV46dlxlVh0Q3sYqjkTKiw1taEUwkAVkuqpQFC3Cn0bk",
	"/GffbtlVTa4M2zQoUjVp1Io6IbA3+shoFhv6MKMZrMPpRDj0xekKpO87ijrt695E0Qt/VySq6uS+3FDf",
	"OkrMPvFM5aXD/KDPJgG/mcGriSf6SBsaMbf/zKiiiHrLh3YBPxzQnAKBDI3MRwYUg1Uo3ZcuNOaA5oqV",
	"xA3FOPlTVeqAPp6C4Edrm1uqTimsRY1rZfFva98lINP6k8K++R5L7YsvKwUV2MnCDZWiadDHXxOOor+h",
	"Hxxdsx+ZDNrWkGMcBgG7rrvtFrDqh1jvWLDNLsEWe7piJAuCN7Q7H6V3gzTjoL5VoSh04E6DhXJzHQcN",
	"B8C+8LTQIIlGJcvk1eL54pWX1bb0pH4dcd7VtSN8v+eNTJbJP9B6jZ1OZ/+Xz58/2dzv7c8M/TcOLrnI",
	"EBitKwAOM39b18KcfCmGxyFhuAfVf0GI0kPKoJOF/sPr2PJ9TfvCv3fcN4IyrNa9Njg79PfzLS/Czaku",
	"g7U+oExBe6i6CVp4AacJF2cHWO0FSR1aSdYa4zLfUUr09S69mJeLXj5daiZy4MK9TDy8R/ECdp6xd644",
	"d565dqDyLhKKgfQwVXtzuWiri/2kP9jocmgcwA8XAxd6peJYoxMEXIfO4PSNnrsVea1IRh4DOXD5wHsL",
	"uMnPRHpsAY7sotp1I4tjo3stI53IB4cYv98FueNtWn8HFuKxIUVZ1UrkM/0fZVCup4rf6sDcvd/TmSNw",
	"/NzAkfZ7972HYRc75y5cD3WiYzLbBFqagnbd7mtl33RtuePC11qengyw45uTu6mWsKbFu/9yrbSNU4Xy",
	"rGaeoBDWXmB34+CDVwezCuCsOgL2LtfH+NbQt63Y3AOTjZq6zh93wxb0y6iYvHTph86IwR61hTqENhwm",
	"C/fFAY3KVdT5bEHZzmwM3oPQbekB4HaXq790zfWbIHesTf8HoZs7NfiNgPuqA+7Z/cREZk7EZC+Rfa7B",
	"6g4qUxyPRo9H4niPIKDGeo8m7Yi/OoVObnRblEDIDrqF0W3DqYO3Jowo924XrUE56OWwcgG3BNxmGTKD",
	"AMLjOJLGcqfoxw3AseQOfDddwIpOY1U79DUQlRsVT1AK6fAtgqRAOQfjwL+/dGH5v2Tgs9A/IYhfwBWI",
	"CwPegFeSMeNi0Hjemp9fOFn+9iVpTZUsk2vRqOvDi+Tu492/BwA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
