// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
)

// Defines values for Outcome.
const (
	Ineligible         Outcome = "ineligible"
	NotLocked          Outcome = "not_locked"
	Unlocked           Outcome = "unlocked"
	VerificationFailed Outcome = "verification_failed"
)

// Valid indicates whether the value is a known member of the Outcome enum.
func (e Outcome) Valid() bool {
	switch e {
	case Ineligible:
		return true
	case NotLocked:
		return true
	case Unlocked:
		return true
	case VerificationFailed:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	AccountRestricted    ProblemCode = "account_restricted"
	AttestationRequired  ProblemCode = "attestation_required"
	BadRequest           ProblemCode = "bad_request"
	DirectoryError       ProblemCode = "directory_error"
	InvalidCredentials   ProblemCode = "invalid_credentials"
	NoSession            ProblemCode = "no_session"
	PresenceMismatch     ProblemCode = "presence_mismatch"
	RateLimited          ProblemCode = "rate_limited"
	SessionExpired       ProblemCode = "session_expired"
	VoucherIsClaimant    ProblemCode = "voucher_is_claimant"
	VoucherMismatch      ProblemCode = "voucher_mismatch"
	VoucherNotAuthorised ProblemCode = "voucher_not_authorised"
	WrongStage           ProblemCode = "wrong_stage"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case AccountRestricted:
		return true
	case AttestationRequired:
		return true
	case BadRequest:
		return true
	case DirectoryError:
		return true
	case InvalidCredentials:
		return true
	case NoSession:
		return true
	case PresenceMismatch:
		return true
	case RateLimited:
		return true
	case SessionExpired:
		return true
	case VoucherIsClaimant:
		return true
	case VoucherMismatch:
		return true
	case VoucherNotAuthorised:
		return true
	case WrongStage:
		return true
	default:
		return false
	}
}

// Defines values for Stage.
const (
	AwaitingClaim        Stage = "awaiting_claim"
	AwaitingConfirmation Stage = "awaiting_confirmation"
	Complete             Stage = "complete"
	Start                Stage = "start"
)

// Valid indicates whether the value is a known member of the Stage enum.
func (e Stage) Valid() bool {
	switch e {
	case AwaitingClaim:
		return true
	case AwaitingConfirmation:
		return true
	case Complete:
		return true
	case Start:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Department  *string `json:"department,omitempty"`
	Description *string `json:"description,omitempty"`
	DisplayName string  `json:"displayName"`
	Mail        *string `json:"mail,omitempty"`
	Title       *string `json:"title,omitempty"`
	Username    string  `json:"username"`
}

// Confirmation defines model for Confirmation.
type Confirmation struct {
	// Attest The voucher attests that they are with the user in person and have confirmed their identity.
	Attest   bool   `json:"attest"`
	Password string `json:"password"`

	// Username The voucher's username, which must be the account that started the session.
	Username string `json:"username"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Password string `json:"password"`

	// Username sAMAccountName, userPrincipalName or DOMAIN\sAMAccountName.
	Username string `json:"username"`
}

// Info defines model for Info.
type Info struct {
	// ConfirmWindowSeconds How long the voucher has to confirm after the user enters their details.
	ConfirmWindowSeconds int `json:"confirmWindowSeconds"`

	// HelpText Optional extra guidance shown when the locked-out user enters their details.
	HelpText *string `json:"helpText,omitempty"`

	// SessionLifetimeSeconds How long a session lasts from the voucher signing in.
	SessionLifetimeSeconds int `json:"sessionLifetimeSeconds"`

	// Title Page title.
	Title string `json:"title"`

	// VoucherDescription Who may vouch for a user, in words the user understands.
	VoucherDescription string `json:"voucherDescription"`
}

// Outcome * `not_locked` - the password works, so the account isn't locked.
// * `unlocked` - the account was unlocked and the password verified.
// * `verification_failed` - the account was unlocked but the password from step 2 was wrong.
// * `ineligible` - this account can't be unlocked by self-service.
type Outcome string

// Problem defines model for Problem.
type Problem struct {
	Code    ProblemCode `json:"code"`
	Message string      `json:"message"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// SessionState defines model for SessionState.
type SessionState struct {
	// ClaimedUsername The username entered in step 2.
	ClaimedUsername *string `json:"claimedUsername,omitempty"`

	// ConfirmBy In `awaiting_confirmation`, when the user's details expire and must be entered again.
	ConfirmBy *time.Time `json:"confirmBy,omitempty"`

	// ExpiresAt When the session expires.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Message A human-readable explanation of the outcome.
	Message *string `json:"message,omitempty"`

	// Outcome * `not_locked` - the password works, so the account isn't locked.
	// * `unlocked` - the account was unlocked and the password verified.
	// * `verification_failed` - the account was unlocked but the password from step 2 was wrong.
	// * `ineligible` - this account can't be unlocked by self-service.
	Outcome *Outcome `json:"outcome,omitempty"`
	Stage   Stage    `json:"stage"`
	Target  *Account `json:"target,omitempty"`
	Voucher *Account `json:"voucher,omitempty"`
}

// Stage defines model for Stage.
type Stage string

// SubmitClaimJSONRequestBody defines body for SubmitClaim for application/json ContentType.
type SubmitClaimJSONRequestBody = Credentials

// ConfirmVouchJSONRequestBody defines body for ConfirmVouch for application/json ContentType.
type ConfirmVouchJSONRequestBody = Confirmation

// SubmitVoucherJSONRequestBody defines body for SubmitVoucher for application/json ContentType.
type SubmitVoucherJSONRequestBody = Credentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetInfo Settings the web interface needs to render
	// (GET /info)
	GetInfo(ctx *echo.Context) error
	// CancelSession Abandon the current unlock session
	// (DELETE /session)
	CancelSession(ctx *echo.Context) error
	// GetSession The current unlock session of this browser
	// (GET /session)
	GetSession(ctx *echo.Context) error
	// SubmitClaim Step 2 - the locked-out user enters their username and password
	// (POST /session/claim)
	SubmitClaim(ctx *echo.Context) error
	// ConfirmVouch Step 3 - the voucher confirms the user's identity and signs in again to unlock
	// (POST /session/confirm)
	ConfirmVouch(ctx *echo.Context) error
	// SubmitVoucher Step 1 - an authorised colleague signs in and starts a session
	// (POST /session/voucher)
	SubmitVoucher(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetInfo(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInfo(ctx)
	return err
}

// CancelSession converts echo context to params.
func (w *ServerInterfaceWrapper) CancelSession(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelSession(ctx)
	return err
}

// GetSession converts echo context to params.
func (w *ServerInterfaceWrapper) GetSession(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSession(ctx)
	return err
}

// SubmitClaim converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitClaim(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitClaim(ctx)
	return err
}

// ConfirmVouch converts echo context to params.
func (w *ServerInterfaceWrapper) ConfirmVouch(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConfirmVouch(ctx)
	return err
}

// SubmitVoucher converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitVoucher(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitVoucher(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/info", wrapper.GetInfo, options.OperationMiddlewares["getInfo"]...)
	router.DELETE(options.BaseURL+"/session", wrapper.CancelSession, options.OperationMiddlewares["cancelSession"]...)
	router.GET(options.BaseURL+"/session", wrapper.GetSession, options.OperationMiddlewares["getSession"]...)
	router.POST(options.BaseURL+"/session/voucher", wrapper.SubmitVoucher, options.OperationMiddlewares["submitVoucher"]...)
	router.POST(options.BaseURL+"/session/claim", wrapper.SubmitClaim, options.OperationMiddlewares["submitClaim"]...)
	router.POST(options.BaseURL+"/session/confirm", wrapper.ConfirmVouch, options.OperationMiddlewares["confirmVouch"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FhLj9vIEf4rBSaAkwVH48cmBwE5yPYmO8CubUDO7mFlSC2ySPaarGa6mpIFY/570C8+NNTMHMZJgNwk",
	"slldVf3VV1/11yRTTasIyXCy/Jpo5FYRo/vzQat9jY39mSkySMb+FG1by0wYqej6d1Zkn3FWYSPsrz9q",
	"LJJl8ofrwe61f8vX0d7t7W2a5MiZlq01kyyTjxWCxn91yAYKIWvMF4ldFT61lldZpjrvQqtVi9pI72aO",
	"rdCmCe6ZU4vJMmGjJZXJ+UZz7yW3tTi9Ew3Ovm+ErGdfGGnq+U86Rk3z9m7TxMYpNebJ8rdh5dSPT2n8",
	"Tu1/x8xYo28UFVI3IgYyTYIwBtn4dJwn9qC6rEINfg2DqYQBU+EJhEY4SlPZf2B9AUnQomZFICiHShwQ",
	"Mr8x5naV1CBzJCPNaZH0Xu6VqlGQdbMVzEelc+tKoay/yXJ4aNP55Sek0lTJ8sXzl9+nSSOpf5Den8uL",
	"oT1jiOtSOFYyq6Dp2MAeXWTCQ8cHzkZo44MBRmapaDH16+Vf/vqAW5dPcRRpOJLZs9TokihqvnuU/7kM",
	"8urnUFXvXObsyg9aUiZbUdtHoDS8ff/z6ubdZjNd/C1SNpepGyrU3RQFSP4qKVfHNWaKcr4b3o/qCLWi",
	"EsyAFKgEg1ER1CAKg3qAP5JBzQHoORohax7hXJLBErV1rMK6/YhfZkruvfshasAvRgsoO5kLyhC4UkeC",
	"Y4Xk9qtV9hnzK9WZR209nGcA7U+yQCMbfDh8EXEOtWDDUGjVTHLCsiRJJUiaj7VnuukGH0SJ4N7N+hms",
	"v53y79TEr5WCRpy8J1AoDcJlIwVJYEHBw9l0lKNmIyify8sZvrzLs05czGA6j6s5WL7vTKbmSuo72JEy",
	"W3+4O7hy7keE24g+cwqsJrQkmZ6ZgIfFhr6DXUdTA3HlUTDEd46gJ9YPqGUhow3/zzfqre+p95rbd2Zq",
	"zsGEDbbw0q08akWlty0Ja1nKfY3epOTeZiZsMHscGT4BY11cMeqDzHCxsUeA1DX2nIZkJWkSP7Hndtf7",
	"JE2GfZNPdxCQjgXLOV/k7qzirnuRb4PccFYPopb5NhuxcpqEgLYa7QaZcQ5oYXBby0b6v6S2AUsDqrb4",
	"pXUoTBOXsS0bUTqe08hIGW4byY0wWTXAc2vTIDpTKS0Z89ELydusFrIRZEZPRxZ8l/F56gvAqgmNmVH6",
	"tEWtlZ5NV4PMonyESnHpG9bPFcTaB782wuBM/m0ImP/z3l4eW4JnQsxBUoDfLL2EWn19umvthmAnjkIa",
	"SeU2G+mmXTrwr93uGUemBX9qrqiidIh+iFJ4Zuy7cS4MXlnqmHPMW+KVmaO7sHkk5LD28cZHZzY1vYKq",
	"awRdaRS52NdoTdeCXNigCrer8qw1m041MNp9Gj4Sn+1DRpQPrl+7RbaHCF2ieWh5FPlD+3j0F2eYZXMR",
	"qtHvyAZOEdpS6iFj4Tp5MNbeqZuZajRzJGTdkEGzTA9oPeLAQI72XAJJrjIjDwhvY9lGPuXFhja0IhjY",
	"ATJV1yjKDuFPoy7+Z9fG2VZNITWb1CtdOREAkoLA2Gt1ZNSLDX2c0SLG4nQiSPritAXStwhJQVPbN1FM",
	"w98libo+2S83FLyDrMLsM89UXjrMJepswnCbabyaeKKOtKERVbvPtCzLqONcahfwwwH1yRPIIPJcZkAy",
	"GIm5/dKmRh9QX7HMcUMxTy6qWh7Q5VMQ/GhM+57qUwpr0eBaGvzb2rUFyJT6LLFv6sdKueLLKkElBrm5",
	"oUq0Lbr8K8JR9jf0g+VndqOYRtNpsozDIGAX2tluAat+OHaOedtsD9hgT1eMZEDwhnbnI/pukHzsVb0s",
	"JflGHLSdLzffeNkD9oWjhRZJtDJZJq8WzxevnFw3lSP164jzUNeW8N2eN3myTP6Bxmn3dHqn8PL58ye7",
	"T3D2Zy4TbixcCpEhMBpbAOzvErqmEfrkStE/9geGe5D9F4SYO0hptHLTfXgde7yraVf4d8J9IyjDet2L",
	"gbOgv59veRFuVl5pbNQB8xSUg6qdzIUThopwcRbAai8oV76VZJ3W9uQDpURfb9OL53LRy6c7mokcuHDf",
	"E4N3KF7AzjH2zhbnzjHXDmQRMiEZSA3TujNXiK6+2E/6wEaXTuMEfryYON8rJccanSDg2ncGq2/U3G3L",
	"a0l55DHIBy4feG8BN8WZ+IeRno/y1o5Clo3utIx0Ih8sYtx+F+ROPyPEfGxIUlZ3OfLYiZEMKjz6+tHQ",
	"KM/cvd/TWcZz/Nwgk/Z7972HYRc7585fOwXRMZmZPC1NQbvu9o00b0JbDlz4WuWnJwPs+EbmdqoljO7w",
	"9r9cK11rVWF+VjNPUAhrP99dPXwlMasAzqrDY+9yfYxvI13bis3dM9moqavicTd3Xr+MislJl8szcikP",
	"vg2HwVZyPzZ7nc8GpAlmY/Luhe4wqys9P3XPITrc5v4Suu43gfRYtP4PYrqwMvEbIfpVQHSvPn0uJvpz",
	"ojJ77exAAEYFDE0BPppJHgnwPYKABps96jR0hPrkW7xWXVkBIVtMl1p1LacW94owwt+5XXYa80FI+5UL",
	"eE/AXZYhMwggPI4zqQ0HqT/uDJY+d+Da7AJWdBrL3aHhgajtDHmCSuQW+MJrDcznYOyJ+ZeQlv9Laj5L",
	"/ROC+AVcgbgw+Q14pTyeuBjEn7PmBhtOlr99TTpdJ8vkWrTy+vAiuf10++8BAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
