// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v5"
)

// Defines values for Outcome.
const (
	Ineligible         Outcome = "ineligible"
	NotLocked          Outcome = "not_locked"
	Unlocked           Outcome = "unlocked"
	VerificationFailed Outcome = "verification_failed"
)

// Valid indicates whether the value is a known member of the Outcome enum.
func (e Outcome) Valid() bool {
	switch e {
	case Ineligible:
		return true
	case NotLocked:
		return true
	case Unlocked:
		return true
	case VerificationFailed:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	AccountRestricted    ProblemCode = "account_restricted"
	AttestationRequired  ProblemCode = "attestation_required"
	BadRequest           ProblemCode = "bad_request"
	DirectoryError       ProblemCode = "directory_error"
	InvalidCredentials   ProblemCode = "invalid_credentials"
	NoSession            ProblemCode = "no_session"
	PresenceMismatch     ProblemCode = "presence_mismatch"
	RateLimited          ProblemCode = "rate_limited"
	SessionExpired       ProblemCode = "session_expired"
	VoucherIsClaimant    ProblemCode = "voucher_is_claimant"
	VoucherNotAuthorised ProblemCode = "voucher_not_authorised"
	WrongStage           ProblemCode = "wrong_stage"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case AccountRestricted:
		return true
	case AttestationRequired:
		return true
	case BadRequest:
		return true
	case DirectoryError:
		return true
	case InvalidCredentials:
		return true
	case NoSession:
		return true
	case PresenceMismatch:
		return true
	case RateLimited:
		return true
	case SessionExpired:
		return true
	case VoucherIsClaimant:
		return true
	case VoucherNotAuthorised:
		return true
	case WrongStage:
		return true
	default:
		return false
	}
}

// Defines values for Stage.
const (
	AwaitingConfirmation Stage = "awaiting_confirmation"
	AwaitingVoucher      Stage = "awaiting_voucher"
	Complete             Stage = "complete"
	Start                Stage = "start"
)

// Valid indicates whether the value is a known member of the Stage enum.
func (e Stage) Valid() bool {
	switch e {
	case AwaitingConfirmation:
		return true
	case AwaitingVoucher:
		return true
	case Complete:
		return true
	case Start:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Department  *string `json:"department,omitempty"`
	Description *string `json:"description,omitempty"`
	DisplayName string  `json:"displayName"`
	Mail        *string `json:"mail,omitempty"`
	Title       *string `json:"title,omitempty"`
	Username    string  `json:"username"`
}

// Confirmation defines model for Confirmation.
type Confirmation struct {
	// Attest The voucher attests that they are with the user in person and have confirmed their identity.
	Attest bool `json:"attest"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Password string `json:"password"`

	// Username sAMAccountName, userPrincipalName or DOMAIN\sAMAccountName.
	Username string `json:"username"`
}

// Info defines model for Info.
type Info struct {
	// ConfirmWindowSeconds How long the voucher has to confirm after signing in.
	ConfirmWindowSeconds int `json:"confirmWindowSeconds"`

	// HelpText Optional extra guidance shown on the first step.
	HelpText *string `json:"helpText,omitempty"`

	// SessionLifetimeSeconds How long a session lasts from step 1.
	SessionLifetimeSeconds int `json:"sessionLifetimeSeconds"`

	// Title Page title.
	Title string `json:"title"`

	// VoucherDescription Who may vouch for a user, in words the user understands.
	VoucherDescription string `json:"voucherDescription"`
}

// Outcome * `not_locked` - the password works, so the account isn't locked.
// * `unlocked` - the account was unlocked and the password verified.
// * `verification_failed` - the account was unlocked but the password from step 1 was wrong.
// * `ineligible` - this account can't be unlocked by self-service.
type Outcome string

// Problem defines model for Problem.
type Problem struct {
	Code    ProblemCode `json:"code"`
	Message string      `json:"message"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// SessionState defines model for SessionState.
type SessionState struct {
	// ClaimedUsername The username entered in step 1.
	ClaimedUsername *string `json:"claimedUsername,omitempty"`

	// ConfirmBy In `awaiting_confirmation`, when the voucher's sign-in expires.
	ConfirmBy *time.Time `json:"confirmBy,omitempty"`

	// ExpiresAt When the session expires.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Message A human-readable explanation of the outcome.
	Message *string `json:"message,omitempty"`

	// Outcome * `not_locked` - the password works, so the account isn't locked.
	// * `unlocked` - the account was unlocked and the password verified.
	// * `verification_failed` - the account was unlocked but the password from step 1 was wrong.
	// * `ineligible` - this account can't be unlocked by self-service.
	Outcome *Outcome `json:"outcome,omitempty"`
	Stage   Stage    `json:"stage"`
	Target  *Account `json:"target,omitempty"`
	Voucher *Account `json:"voucher,omitempty"`
}

// Stage defines model for Stage.
type Stage string

// SubmitClaimJSONRequestBody defines body for SubmitClaim for application/json ContentType.
type SubmitClaimJSONRequestBody = Credentials

// ConfirmVouchJSONRequestBody defines body for ConfirmVouch for application/json ContentType.
type ConfirmVouchJSONRequestBody = Confirmation

// SubmitVoucherJSONRequestBody defines body for SubmitVoucher for application/json ContentType.
type SubmitVoucherJSONRequestBody = Credentials

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetInfo Settings the web interface needs to render
	// (GET /info)
	GetInfo(ctx *echo.Context) error
	// CancelSession Abandon the current unlock session
	// (DELETE /session)
	CancelSession(ctx *echo.Context) error
	// GetSession The current unlock session of this browser
	// (GET /session)
	GetSession(ctx *echo.Context) error
	// SubmitClaim Step 1 - the locked-out user enters their username and password
	// (POST /session/claim)
	SubmitClaim(ctx *echo.Context) error
	// ConfirmVouch Step 3 - the voucher confirms the user's identity and the account is unlocked
	// (POST /session/confirm)
	ConfirmVouch(ctx *echo.Context) error
	// SubmitVoucher Step 2 - a colleague signs in to vouch for the user
	// (POST /session/voucher)
	SubmitVoucher(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetInfo(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInfo(ctx)
	return err
}

// CancelSession converts echo context to params.
func (w *ServerInterfaceWrapper) CancelSession(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelSession(ctx)
	return err
}

// GetSession converts echo context to params.
func (w *ServerInterfaceWrapper) GetSession(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSession(ctx)
	return err
}

// SubmitClaim converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitClaim(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitClaim(ctx)
	return err
}

// ConfirmVouch converts echo context to params.
func (w *ServerInterfaceWrapper) ConfirmVouch(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConfirmVouch(ctx)
	return err
}

// SubmitVoucher converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitVoucher(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitVoucher(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/info", wrapper.GetInfo, options.OperationMiddlewares["getInfo"]...)
	router.DELETE(options.BaseURL+"/session", wrapper.CancelSession, options.OperationMiddlewares["cancelSession"]...)
	router.GET(options.BaseURL+"/session", wrapper.GetSession, options.OperationMiddlewares["getSession"]...)
	router.POST(options.BaseURL+"/session/claim", wrapper.SubmitClaim, options.OperationMiddlewares["submitClaim"]...)
	router.POST(options.BaseURL+"/session/voucher", wrapper.SubmitVoucher, options.OperationMiddlewares["submitVoucher"]...)
	router.POST(options.BaseURL+"/session/confirm", wrapper.ConfirmVouch, options.OperationMiddlewares["confirmVouch"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fjdj+O2Ef9XBmqBAwKt9z7SPhjow+YuaBZIsgd4kzzEB5uWxtJkpaHKoewzDv7fC5KiLNnybQrcoQX6",
	"pg9yOB+/+c0MPyWZrhvNyFaS+afEoDSaBf3Le6M3FdbuMdNska17VE1TUaYsab79QzS7b5KVWCv39FeD",
	"22Se/OX2JPc2/JXbKO94PKZJjpIZapyYZJ48lggG/9WiWNgqqjCfJW5Vt9VJvssy3QYVGqMbNJaCmjk2",
	"yti6U88eGkzmiVhDXCTnB039J2kqdfhZ1Tj5v1ZUTf6wZKvpLa2g4Wl5xzRxdpLBPJn/flo51uNDGvfp",
	"zR+YWSf0reYtmVpFQ8ZOUNai2OCOc8fudJuVaCCsEbClsmBLPIAyCHuypXsDpwsQQ4NGNIPiHEq1Q8jC",
	"wZi7VWSAcmRL9jBLei03Wleo+MK8TqtJcwx6OaqSS2saJbLXJnfPW+2MTuanjy4mH39ELmyZzF+9fP1t",
	"mtTE/Yf08wEZ+0fufuqA5Ryfeie8N8QZNapyn0AbePfw0939z8vlePFsrMjrv/39GT2ux743bcpT97zV",
	"ly7qovIbca73C8w053Jp3g96D5XmAuwAB6USsDrGFdTWogGhgokLIB7EldhigcZpUWLVPOLHCYg9+AdV",
	"AX60RkHRUq44Q5BS7xk0+7O3ZMSCWGxmyYVj0kRQhDT/SFu0VOPz9ijotkClHKa3RtdePLya1r/P1rHA",
	"96pA8P8m9epc9m7MIWMRv5UaanUI7oWtNqA8jFKXTC6qckqvlnM0YhXnMkueA0hQeVKJqx5Lp4ExhauH",
	"1mZ6Kie+gTVru6p09oT5Gm68+hGizqInSUG0/6xCPgAJv7AQtsyW/A2sWx4LiCv3SiD+8yQzkr5DQ1uK",
	"MsJbKDarUBc+K27T2rG4ASz8yr3RXATZxFhRQZsKg0iSXmamnDEbHAg+gGC1vRE0O8pwtnQhQG5rF6eT",
	"s5I0iVtc3C61T9LkdG7y4QIB6bDonid87mMVT92ofNWVTC91pyrKV9mAVtOkM2hl0B2QWa+AURZXFdUU",
	"XlmvOiydULXCj41HYZp4j63EqsITlUFBznBVk9TKZuUJnivnBtXaUhsSzAc/SFZZpahW7DQNNSE4pUe7",
	"K38GM6vNYYXGaDPpmxpFVPEnyqr31Wn9FPoXwdKFVRYnnO30xfyXq3Xjscto9xeQLRrMXb5fUNBJ+y4x",
	"vztcSrtnWKu9IktcrLJBoV+nsC+Rh/T9QjxX3xBDiJJnkr5K5srijWOEKRW6DXd2isW6YyKv/sfCB9EZ",
	"i76Dsq0V3xhUudpU6ERXir2BoLf+VB3IaNJx+kRUn2svI5+5cmJV8ez6hV/kSoMyBdrnlsf+81QV/vSO",
	"M3SKvQrKqHdMcrHK+KSJ4IhHp8kkXjz/102FdopdnCLUdRPjEC0G5NaxnotMx353maUdwruYopEoZbbk",
	"Jd+F0rYvtQzrQdzcGL1DCf3mE+s9kJWeoFP3nUFBpqsKVdFioGzFSz5xCRRGt42HvQD1PYW43NsYvXfH",
	"u0oSnHNqcINiJE63oIDP6yVbDRucwfc7NIeQsqEJOnUqJGDJtbzatxpmh+ZGKD+lhz+jImcasdf3B2ub",
	"B64OKSxUjQuy+I+FZ13ItH4i7GvmvtQ+CbJScYGxHStV0yAH83qzvIO/N0Yb8c26QdsadoVTQMG6Kxbr",
	"Gdz145NXLIgWcESLULfiy5kgW1Cy5PX5ELcObu+9qg0VxKHMdZ1TQH0oaxJQ88pnZ4OsGkrmyZvZy9kb",
	"383a0rPobQRbl16OYf2Z93kyT/6J1re26XjqfP3y5RebOL38iXHzni2arcqcS6xLIgnTZlvXyhx8PoTP",
	"IV64Aep3MGLuA2bQNXN+422soD6xfPZdmPvWNcXVoi+1Z0Z/O11jItxc82Kw1jvMU9AeqW52U77t0oyz",
	"MwPuNorzLk+y1hgX+S6vo67H9Gpcrmr55UIzqr9XbgSi8R7FM1h74ly73Fx7YlwDbTtPkADruGEW5v6t",
	"aqurtN4bNriWGDrw8arjQskiiTk6QsCtZxh3aKOn5vG3JWZPMm5SNwfYEOdu+rKBIfpmaAb327M+O/Kq",
	"AsZ91GnJ5JPd2EFTHU10myhAYX1eSNbgndqfM27zl3ytx588ZB1rzzrcKnSFezROBE4ZI27Rbmqyb73n",
	"QqlEsd/p/PDF0Da8bTiO67E1LR7/y0AfRLID+xdA8CKMPWFcCt6/0a0NRdG3rNLd6PSNrAtqRMAZrEOT",
	"cR3Yv/gckSFYu+LejXRnoC9oF6pdN52pQhGLBbIzeBzgasmfA9ZpyNRmelycwlt3lfZrV9C+CuCGTdn/",
	"IOK25G5svg7m3nSYi/dNHXZO1yAvpL9E7HlkQHAxqGMEDpruaQQOrzpjx6OgxnqDJu0otTqE4ml0W5TA",
	"KDZ2l5I6XteMcSLxWhetwXzJUWxYOYMHBmmzDEWeJ9rROBfY1hm9ZOKsavMuL3K0iiqJh0dvbNBVheiQ",
	"2ED2jlUMmSso7mt9nVl/7YeG/0NubRs3teZfCeuv4WY0vfQzitWDC8EI/KBjGCckmf/+KWlNlcyTW9XQ",
	"7e5Vcvxw/PcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
