#!/bin/bash
# Build (if needed) and start the disposable Samba AD DC, then populate it.
#   LDAP:  ldap://127.0.0.1:10389   (simple binds allowed)
#   LDAPS: ldaps://127.0.0.1:10636  (self-signed cert generated by Samba)
# Set REBUILD=1 to force an image rebuild.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE="${IMAGE:-localhost/vouch-samba-test}"
CONTAINER="${CONTAINER:-vouch-samba-test}"
LDAP_PORT="${LDAP_PORT:-10389}"
LDAPS_PORT="${LDAPS_PORT:-10636}"

if [ "${REBUILD:-0}" = 1 ] || ! podman image exists "${IMAGE}"; then
    podman build -t "${IMAGE}" -f "${HERE}/Containerfile" "${HERE}"
fi

if podman container exists "${CONTAINER}"; then
    if [ "$(podman inspect -f '{{.State.Running}}' "${CONTAINER}")" != true ]; then
        podman start "${CONTAINER}" >/dev/null
    fi
    echo "start: container ${CONTAINER} already exists (run stop.sh for a fresh domain)"
else
    podman run -d --name "${CONTAINER}" --hostname dc1 \
        -p "127.0.0.1:${LDAP_PORT}:389" \
        -p "127.0.0.1:${LDAPS_PORT}:636" \
        "${IMAGE}" >/dev/null
fi

echo -n "start: waiting for LDAP on 127.0.0.1:${LDAP_PORT}"
for _ in $(seq 1 120); do
    if [ "$(podman inspect -f '{{.State.Running}}' "${CONTAINER}")" != true ]; then
        echo; echo "start: container exited:" >&2
        podman logs --tail 50 "${CONTAINER}" >&2
        exit 1
    fi
    # Check from inside the container so the host needs no LDAP client tools.
    if podman exec "${CONTAINER}" ldapwhoami -x -H ldap://127.0.0.1 \
        -D "Administrator@vouch.test" -w 'Admin-Passw0rd!' >/dev/null 2>&1; then
        echo " up"
        break
    fi
    echo -n .
    sleep 2
done

"${HERE}/setup.sh"
